import { Fragment, useEffect, useMemo, useState } from 'react'
import { Loader2 } from 'lucide-react'

import { Badge, StatusDot } from '@/components/ui/badge'
import { api } from '@/lib/api'
import { NODE_TYPE_LABEL, nodeColor } from '@/lib/graphColors'
import type { AssetDoc, GraphData, GraphLink, GraphNode } from '@/lib/types'

function endId(end: string | GraphNode): string {
  return typeof end === 'object' ? end.id : end
}

/** Inspector for a selected graph node. Asset nodes render as an OKF concept
 *  document (front matter + consolidated knowledge); other nodes fall back to
 *  a plain relationships view. */
export function NodeInspector({ node, data }: { node: GraphNode; data: GraphData }) {
  if (node.type === 'asset' && node.id.startsWith('asset:')) {
    return <AssetInspector unifiedId={node.id.slice('asset:'.length)} />
  }
  return <PlainInspector node={node} data={data} />
}

/** OKF-shaped, two-part view: front matter + consolidated knowledge body. */
function AssetInspector({ unifiedId }: { unifiedId: string }) {
  const [doc, setDoc] = useState<AssetDoc | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const controller = new AbortController()
    setLoading(true)
    setError(null)
    setDoc(null)
    api
      .asset(unifiedId, controller.signal)
      .then((d) => {
        if (d.error) setError('Asset not found in the index.')
        else setDoc(d)
      })
      .catch((e) => {
        if (!(e instanceof DOMException && e.name === 'AbortError')) {
          setError(e instanceof Error ? e.message : 'Failed to load asset')
        }
      })
      .finally(() => setLoading(false))
    return () => controller.abort()
  }, [unifiedId])

  if (loading) {
    return (
      <div className="flex items-center gap-2 py-6 text-sm text-muted-foreground">
        <Loader2 className="size-4 animate-spin" />
        Loading asset knowledge…
      </div>
    )
  }
  if (error || !doc) {
    return <p className="py-4 text-sm text-muted-foreground">{error ?? 'No data.'}</p>
  }

  return (
    <div className="space-y-5">
      {/* ── Front matter (the OKF document header) ───────────────────── */}
      <div>
        <div className="flex items-center gap-2 text-xs font-medium text-muted-foreground">
          <span
            className="size-2.5 rounded-full"
            style={{ background: nodeColor('asset') }}
            aria-hidden
          />
          {doc.type}
          {doc.needs_review ? (
            <Badge variant="review" className="ml-1">
              needs review
            </Badge>
          ) : (
            <span className="flex items-center gap-1 text-verified">
              <StatusDot tone="verified" />
              resolved
            </span>
          )}
        </div>
        <h3 className="mt-1.5 text-lg font-semibold leading-tight tracking-tight">
          {doc.title}
        </h3>
        <p className="mt-0.5 font-mono text-xs text-muted-foreground">{doc.unified_id}</p>

        {/* Aliases: each identifier value + which sources asserted it */}
        {doc.aliases.length > 0 && (
          <div className="mt-3 space-y-2">
            <p className="text-xs font-medium text-muted-foreground">Also known as</p>
            <ul className="space-y-1.5">
              {doc.aliases.map((a, i) => (
                <li key={i} className="flex flex-wrap items-center gap-x-2 gap-y-1 text-sm">
                  <span className="font-mono">{a.value}</span>
                  <span className="text-xs text-muted-foreground">
                    {a.concept.replace(/_/g, ' ')}
                  </span>
                  {a.sources.map((s) => (
                    <span
                      key={s}
                      className="rounded-full bg-secondary px-2 py-0.5 text-[11px] text-secondary-foreground"
                    >
                      {s}
                    </span>
                  ))}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      {/* ── OKF concept body, rendered as-is ─────────────────────────── */}
      <OkfBody markdown={doc.markdown} title={doc.title} />
    </div>
  )
}

// ── OKF markdown renderer ───────────────────────────────────────────────
// The OKF document is generated by our own backend (`_render_okf_markdown`),
// so its shape is fixed: YAML front matter, a `# {title}`, `## {relation}`
// sections whose bullets are `- **connector** (date) — \`record_id\`` with
// nested `  - text` / `  - key: value` lines, a `## Related assets` list, and
// a `# Citations` block. We render that faithfully — one grounded document, no
// duplicated summary cards.

interface OkfListItem { text: string; children: string[] }
type OkfBlock =
  | { kind: 'h1'; text: string }
  | { kind: 'h2'; text: string }
  | { kind: 'list'; items: OkfListItem[] }
  | { kind: 'citation'; text: string }
  | { kind: 'p'; text: string }

function stripFrontmatter(md: string): string {
  const lines = md.split('\n')
  if (lines[0]?.trim() !== '---') return md
  const end = lines.indexOf('---', 1)
  return end === -1 ? md : lines.slice(end + 1).join('\n')
}

function parseOkfBody(md: string, title: string): OkfBlock[] {
  const lines = stripFrontmatter(md).split('\n')
  const blocks: OkfBlock[] = []
  let i = 0
  while (i < lines.length) {
    const line = lines[i]
    if (!line.trim()) { i++; continue }
    if (line.startsWith('## ')) {
      blocks.push({ kind: 'h2', text: line.slice(3).trim() })
      i++
      continue
    }
    if (line.startsWith('# ')) {
      const text = line.slice(2).trim()
      // the body repeats the title as an H1 — drop it (already in the header)
      if (text !== title) blocks.push({ kind: 'h1', text })
      i++
      continue
    }
    if (line.startsWith('- ') || line.startsWith('  - ')) {
      const items: OkfListItem[] = []
      while (i < lines.length && (lines[i].startsWith('- ') || lines[i].startsWith('  - '))) {
        const l = lines[i]
        if (l.startsWith('  - ')) {
          const child = l.slice(4)
          if (items.length) items[items.length - 1].children.push(child)
          else items.push({ text: '', children: [child] })
        } else {
          items.push({ text: l.slice(2), children: [] })
        }
        i++
      }
      blocks.push({ kind: 'list', items })
      continue
    }
    // `[1] record-id` citation rows sit under the Citations heading
    if (/^\[\d+\]\s/.test(line)) blocks.push({ kind: 'citation', text: line })
    else blocks.push({ kind: 'p', text: line })
    i++
  }
  return blocks
}

/** Render inline `**bold**`, `` `code` `` and `[label](url)` markdown. */
function renderInline(text: string): React.ReactNode {
  const parts = text.split(/(\*\*[^*]+\*\*|`[^`]+`|\[[^\]]+\]\([^)]+\))/g)
  return parts.map((part, k) => {
    if (!part) return null
    if (part.startsWith('**') && part.endsWith('**')) {
      return <strong key={k} className="font-semibold text-foreground">{part.slice(2, -2)}</strong>
    }
    if (part.startsWith('`') && part.endsWith('`')) {
      return (
        <code key={k} className="rounded bg-secondary px-1 py-0.5 font-mono text-[11px] text-foreground/80">
          {part.slice(1, -1)}
        </code>
      )
    }
    const link = part.match(/^\[([^\]]+)\]\(([^)]+)\)$/)
    if (link) {
      // internal /assets links are visual (no SPA navigation from the inspector)
      return <span key={k} className="font-medium text-primary">{link[1]}</span>
    }
    return <Fragment key={k}>{part}</Fragment>
  })
}

/** Is a nested bullet a `key: value` field rather than free text? */
function fieldOf(child: string): { key: string; value: string } | null {
  const m = child.match(/^([a-z][a-z_]*): ([\s\S]*)$/)
  return m ? { key: m[1], value: m[2] } : null
}

function OkfBody({ markdown, title }: { markdown: string; title: string }) {
  const blocks = useMemo(() => parseOkfBody(markdown, title), [markdown, title])
  if (blocks.length === 0) {
    return (
      <p className="border-t border-border/70 pt-4 text-sm text-muted-foreground">
        No source records linked to this asset yet.
      </p>
    )
  }
  return (
    <div className="space-y-4 border-t border-border/70 pt-4">
      {blocks.map((b, i) => {
        switch (b.kind) {
          case 'h1':
            return (
              <h4 key={i} className="text-sm font-semibold tracking-tight text-foreground">
                {b.text}
              </h4>
            )
          case 'h2':
            return (
              <p key={i} className="pt-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                {b.text}
              </p>
            )
          case 'citation':
            return (
              <p key={i} className="font-mono text-[11px] leading-relaxed text-muted-foreground">
                {b.text}
              </p>
            )
          case 'p':
            return (
              <p key={i} className="text-sm leading-relaxed text-foreground/90">
                {renderInline(b.text)}
              </p>
            )
          case 'list':
            return (
              <ul key={i} className="space-y-2.5">
                {b.items.map((it, j) => (
                  <li
                    key={j}
                    className="rounded-xl border border-border/60 bg-card px-3 py-2.5"
                  >
                    {it.text && (
                      <p className="text-sm leading-snug text-foreground/90">
                        {renderInline(it.text)}
                      </p>
                    )}
                    {it.children.length > 0 && (
                      <dl className="mt-1.5 space-y-1 text-xs">
                        {it.children.map((c, ci) => {
                          const f = fieldOf(c)
                          if (f) {
                            return (
                              <div
                                key={ci}
                                className="grid grid-cols-[auto_1fr] gap-x-3"
                              >
                                <dt className="text-muted-foreground">
                                  {f.key.replace(/_/g, ' ')}
                                </dt>
                                <dd className="text-foreground/80">{f.value}</dd>
                              </div>
                            )
                          }
                          return (
                            <p key={ci} className="leading-relaxed text-foreground/80">
                              {renderInline(c)}
                            </p>
                          )
                        })}
                      </dl>
                    )}
                  </li>
                ))}
              </ul>
            )
        }
      })}
    </div>
  )
}

/** Fallback for non-asset nodes: direct relationships from the current view. */
function PlainInspector({ node, data }: { node: GraphNode; data: GraphData }) {
  const labelById = useMemo(() => {
    const m = new Map<string, GraphNode>()
    for (const n of data.nodes) m.set(n.id, n)
    return m
  }, [data.nodes])

  const relationships = useMemo(() => {
    const out: { relation: string; dir: 'to' | 'from'; other: GraphNode }[] = []
    for (const l of data.links as GraphLink[]) {
      const s = endId(l.source)
      const t = endId(l.target)
      if (s === node.id) {
        const other = labelById.get(t)
        if (other) out.push({ relation: l.relation, dir: 'to', other })
      } else if (t === node.id) {
        const other = labelById.get(s)
        if (other) out.push({ relation: l.relation, dir: 'from', other })
      }
    }
    return out
  }, [data.links, labelById, node.id])

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 text-xs font-medium text-muted-foreground">
        <span
          className="size-2.5 rounded-full"
          style={{ background: nodeColor(node.type) }}
          aria-hidden
        />
        {NODE_TYPE_LABEL[node.type]}
      </div>
      <h3 className="text-lg font-semibold tracking-tight">{node.label}</h3>
      <p className="font-mono text-xs text-muted-foreground">{node.id}</p>

      {relationships.length > 0 ? (
        <div className="border-t border-border/70 pt-4">
          <p className="mb-2 text-sm font-medium">Direct relationships</p>
          <ul className="space-y-2.5">
            {relationships.map((r, i) => (
              <li key={i} className="text-sm">
                <span className="text-xs text-muted-foreground">
                  {r.relation.toLowerCase().replace(/_/g, ' ')} · {r.dir}
                </span>
                <div className="flex items-center gap-2">
                  <span
                    className="size-2 rounded-full"
                    style={{ background: nodeColor(r.other.type) }}
                    aria-hidden
                  />
                  {r.other.label}
                </div>
              </li>
            ))}
          </ul>
        </div>
      ) : (
        <p className="border-t border-border/70 pt-4 text-sm text-muted-foreground">
          No linked records in the current view.
        </p>
      )}
    </div>
  )
}
